### ISSUE TITLE
Attended Check-in did not properly install 

### ISSUE THREAD

**Issue by paultedder** [KingdomFirst/rock-attended-checkin#25]
When clicking the install button on the Rock Shop, the install did not properly download all the necessary pages that were needed for the installation.  It could have been due to multiple clicking of the install button or closing out of the window early... I don't know.  With no ability to remove the install I am stuck moving forward with the module.  
![screen shot 2017-04-11 at 12 08 10 pm](https://cloud.githubusercontent.com/assets/16594749/24919700/8ba6005a-1eb2-11e7-9be8-a2ee6314b705.png)
![screen shot 2017-04-11 at 12 08 21 pm](https://cloud.githubusercontent.com/assets/16594749/24919703/8e34bfdc-1eb2-11e7-9b9b-bd4e834bc91e.png)
![screen shot 2017-04-11 at 12 08 40 pm](https://cloud.githubusercontent.com/assets/16594749/24919707/90d58ec4-1eb2-11e7-9df2-7b6abc454e42.png)

contact info -- ptedder@fellowshipgreenville.org

**Comment by dcs619** [comment]
This is due to the `Childhood Information` attribute category being renamed and the migration not being able to match it.  Leaving open until I can change the migration lookup to use the category GUID.
