### ISSUE TITLE
Prevent Duplicate Check-in not working?

### ISSUE THREAD

**Issue by caseydierking** [KingdomFirst/rock-attended-checkin#27]
I was testing this out earlier today, and when selecting the "Prevent Duplicate Check-in" setting under the Check-in configuration, Attended Check-in still allows me to check in again.

Is this normal? Does it work with Attended Check-in?

**Comment by dcs619** [comment]
Sorry for the late response, this is an unsupported option as noted in the [docs](https://github.com/NewSpring/rock-attended-checkin/blob/master/Attended%20Checkin.md#unsupported-options).

**Comment by dcs619** [comment]
Closing as this behavior is needed in order to support assignment changes or checkouts.
