### ISSUE TITLE
CSS styles make page/block management difficult

### ISSUE THREAD

**Issue by mikejed** [KingdomFirst/rock-attended-checkin#28]
## Admin bar buttons inaccessible:
The styles.css file included with the store version of the plugin includes a directive (line 312) to make all .btn class elements `width=100%` . This affects the built-in buttons on the admin bar, when viewing the pages using the Rock and Stark themes: only the block settings button is visible/accessible.
![fullwidthbuttonbarbuttons](https://cloud.githubusercontent.com/assets/6932047/26287398/9fbe68b0-3e2f-11e7-8b69-7500e5f01ac7.JPG)
Reference http://shouldertheboulder.com/Article?id=555 for the process some churches have had to come up with in order to
> "use the stock Admin block on the Attended Check-in > Administration page instead."

per the documentation.

Adding the following line after `.btn { }` cleared up that issue for me:
`.button-bar .btn {width:inherit;}`

I recommend either using that line, or editing the .btn css overrides to be more limited in their scope, for ease of use.

## Checkin footer
Having made that change, when you add the stock `Checkin -> Administration` block to a page within the attended checkin site, .checkin-footer (which contains the OK button) is set to "position:relative" which causes the button it to show up behind the form and be inaccessible.
![checkin-footer-relative](https://cloud.githubusercontent.com/assets/6932047/26287459/b44a360a-3e30-11e7-9d4e-84ff8f64ad7e.JPG)
Adding `<style>.checkin-footer {position:absolute;}</style>` to the page's Header Content setting also clears up that issue, but perhaps there's another solution more in-keeping with the theming of the plugin?

## Modal dialog scrolling
Finally, something in the styling causes the page settings dialog to not scroll any longer: if I go to the "Advanced" tab and make a change (such as the above style, or setting a page route), I have to go back to the "Basic Settings" tab in order to have access to the save button.
![attended-checkin-page-settings](https://cloud.githubusercontent.com/assets/6932047/26287461/c74868b2-3e30-11e7-9b61-59006e1517ac.JPG)

**Comment by dcs619** [comment]
More fixes in 26c11028cc51fa4041a1736ed6b470f8f499b5cd
