### ISSUE TITLE
Editing Mobile Number Stores as Second Home Number

### ISSUE THREAD

**Issue by bobrufenacht** [KingdomFirst/rock-attended-checkin#48]
Hi David,

I'm still running to pre-release version of Attended Check-In you gave me.  The Update Profile button pre-populates the Phone field with the Mobile phone number.  However, if I edit the number, it stores it as a second Home number with SMS enabled.  I end up with two home numbers and one mobile showing on the person profile page and the second Home number can only be deleted by going directly to the database.  The regular edit shows the other two numbers.

Thanks,
Bob Rufenacht

**Comment by dcs619** [comment]
You'll want to upgrade to the latest version through the Rock shop.  The Update Profile block has updated functionality and a block setting for the default phone type to store it appropriately:

<img width="457" alt="screenshot 2018-08-27 16 40 40" src="https://user-images.githubusercontent.com/1210933/44684872-261a6080-aa18-11e8-8cdc-4b9300c11d9d.png">

**Comment by krallsm** [comment]
I would just like to mention, the version (pretty sure 1.2 based of release notes) that allows this is not available on the Rock Shop. If it is available it requires an update to 8.0 according to the Rock shop for any subsequent updates past 1.1.

**Comment by dcs619** [comment]
Attended Checkin 1.2 targets Rock 7.5, which is an important security update.  The 1.3 and 1.4 updates are for 8.0.
