### ISSUE TITLE
Has Special Needs

### ISSUE THREAD

**Issue by jdouglas2005** [KingdomFirst/rock-attended-checkin#51]
Attended Check-in seems to have installed a group attribute called "Has Special Needs" but there is no qualifier to enable or disable this option by group or group type, so every group has this group attribute displaying on both internal and external sites.

**Comment by dcs619** [comment]
Did you remove the GroupType called `Check in By Special Needs`?  That's the only GroupType that the attribute should target.  Run this query in Admin Tools > Power Tools > SQL Command:

`SELECT ID, Name, Guid FROM GroupType WHERE Name = 'Check in By Special Needs'`

Go to Admin Tools > System Settings > Entity Attributes and filter the list by the Group Entity.  You should see the `Has Special Needs` attribute and can click the row to limit it to the Checkin By Special Needs GroupType.

![screenshot 2018-09-20 12 02 57](https://user-images.githubusercontent.com/1210933/45831414-4e227a00-bccd-11e8-8c9d-e103d8aa597b.png)

**Comment by jdouglas2005** [comment]
Thanks!  Worked beautifully!

JAKE DOUGLAS
MINISTRY ANALYST
VALLEY REAL LIFE

1831 S. BARKER RD., GREENACRES, WA 99016
P: 509.232.0840    F: 509.232.0848     W: WWW.VRL.CHURCH<http://www.valleyreallife.org/>
SERVICE TIMES: THURSDAYS @ 6:30PM & SUNDAYS @ 8, 9:30 & 11:00AM

**Comment by dcs619** [comment]
What was the result of that query?  Was the grouptype deleted?

**Comment by jdouglas2005** [comment]
It had not been deleted. It displayed ID number 36. I updated the group entity with the qualifier of grouptypeid is 36 and it worked great to remove the group type attribute from my other small groups.

Thanks so much!

On Sep 21, 2018, at 9:14 AM, David Stevens <notifications@github.com<mailto:notifications@github.com>> wrote:


What was the result of that query? Was the grouptype deleted?
