### ISSUE TITLE
Issues on Ipad

### ISSUE THREAD

**Issue by krallsm** [KingdomFirst/rock-attended-checkin#52]
We have an issue where in order to select/deselect fully any of our check in areas, you have to essentially double tap. One tap on the checkin type and one tap somewhere outside the box to have a full selection/deselection.

We as well have an issue with not being able to see the "x" to deselect the selected schedule/location in the edit screen. 

It would also be helpful to be able to zoom out or control the size of the top bar where you enter a name or phone number similar to the windows application.

**Comment by BEGamache** [comment]
The double tap I believe is a HTML hover issue. Essentially the mouse is still hovering over the item causing it to remain lit. 
For the view/zoom you could zoom out in the window by pressing CTRL and - (minus)

**Comment by dcs619** [comment]
All the checkin themes have a button hover color that almost matches the button selected state.  The iPad probably isn't clearing the hover but I don't have a way to test.  I've updated the styles to shift over the X button on Edit Activity.

**Comment by BEGamache** [comment]
This is what I added to my styles file to correct it:
```
/* Person Selection on Family Select Page*/
.no-hover:hover {
  background-color: rgba(0,0,0,0.6);
}
```

I also updated the toggle script at the end of the FamilySelect file to this:
```
function togglePerson(element) {
        $(element).toggleClass('active no-hover').blur();
```


You could use this and not mess with JS--this just affects other buttons in the long run.
```
/* Person Selection on Family Select Page*/
.btn-checkin-select:hover {
  background-color: rgba(0,0,0,0.6);
}
```
