### ISSUE TITLE
Add Known Relationship Option

### ISSUE THREAD

**Issue by edcylam** [KingdomFirst/rock-attended-checkin#54]
When creating a new family, adding a new family member, or adding a visitor, we would like to have an option to specify the relationship between the adult and the kid. Of course, the default would be parent for the adult and child for the kid.

**Comment by dcs619** [comment]
Unfortunately there's not enough display space to add that relationship field, but there is a default "Can Checkin" relationship created for family members and any visitors under 18 y/o.
