### ISSUE TITLE
Cut After Last Label

### ISSUE THREAD

**Issue by craigmash** [KingdomFirst/rock-attended-checkin#56]
Would be great if this plugin could also do the cut after last label mod (http://shouldertheboulder.com/Article?id=497).

**Comment by dcs619** [comment]
If you use Server Print, Attended Checkin automatically applies a command (^XB) for all-but-the-last label being output to the printer.  This causes the printer to delay cutting until the last label (no ^XB code).  

This functionality is not implemented for Client Print labels and adding the NewPointe code would be overkill.  It's possible to manually configure Client Print labels with ^XB, but the order of those labels has to be consistent.
