### ISSUE TITLE
Install is incomplete or non-functional

### ISSUE THREAD

**Issue by MCoulterFBCN** [KingdomFirst/rock-attended-checkin#58]
I installed the plug-in on top of v.8.3.  It creates the site but it only opens a blank page with background image.  I see another person mention an issue with installing to an external server.  That is our case but I do not know what their resolution was to the issue.

**Comment by dcs619** [comment]
You should check that you have the correct URL's set in your Sites panel.  You can use the link http://[yourRockinstance]/Sites to make sure one of those is set to respond to the right URL.  

Without those URL's set correctly, Rock responds with the most recently created site it finds, which is Attended Checkin.
