### ISSUE TITLE
Update Notifications

### ISSUE THREAD

**Issue by TeresaReed40** [KingdomFirst/rock-attended-checkin#62]
Hello!  

We recently updated Rock to v.8.5 and experienced problems with the check-in app, not knowing that there was also an update for the app.  Is it possible to get a notification when an update for the app is available...?

Thank you!

**Comment by dcs619** [comment]
Unfortunately Rock doesn't provide a way for plugins to send update notifications - the notifications block only appears for core updates.  You can download the [Rock Shop notifications](https://www.rockrms.com/Plugin/69) plugin but it doesn't trigger on Rock updates either.
