### ISSUE TITLE
Add New Family shows error of needing name & gender because of auto-filling

### ISSUE THREAD

**Issue by tbunney** [KingdomFirst/rock-attended-checkin#67]
When adding a new family in Attended Checkin I keep getting an error that a first name, last name, and gender are needed, when I hit save, even though it is already provided.  It is because it auto-fills the last name in the rest of the rows and wants those filled in also. If you clear those auto-populated last names out, it works, but it is an inconvenience to do this on a busy Sunday morning.

![image](https://user-images.githubusercontent.com/37702418/52728646-abbda880-2f85-11e9-9b92-ac9643bd7030.png)

**Comment by dcs619** [comment]
Confirmed this slipped through testing -- we'll get it fixed.  Thanks for filing an issue!
