### ISSUE TITLE
Keypad showing on Attended Search Page

### ISSUE THREAD

**Issue by kyeschung** [KingdomFirst/rock-attended-checkin#69]
Issue: Keypad showing on Attended Search Page when block setting is disabled.

In the block setting, there's a "Show Key Pad" and we've marked it as "No." But we still see the keypad on the Attended Search Page. Before we updated the plugin, it didn't show the keypad (we updated a couple of versions up after updating to v8 so not sure which one), but it's now showing it regardless of the block setting.

**Comment by SarahCKopf** [comment]
I couldn't replicate this bug.
