### ISSUE TITLE
Override Check In not Listing All Family

### ISSUE THREAD

**Issue by treyhendon** [KingdomFirst/rock-attended-checkin#71]
I appears that the override button is not reloading the family to include all members.  Presumably it is only allowing override for family members that meet a base requirement.

When Override is selected, all family members should be displayed.  i.e.  If a student did not have a grade or birth date marked on their record, they should still be displayed to be allowed to check in when in override mode.

**Comment by karenn-ccbc** [comment]
I just tested live on a Sunday and the override button is working as I had wanted to allow other people int he family to come up so that they could be edited! I believe it is a problem when you only have Already Belongs options only on the config. It worked as I desired today.
