### ISSUE TITLE
Not recognizing Check In By DataView

### ISSUE THREAD

**Issue by MicahO** [KingdomFirst/rock-attended-checkin#73]
This week we switched our check-in rules to "By Data View" from "By Age/Grade." All of our unattended checkin stations work fine, but at our attended check-in we now have the option to check parents into rooms they should not be able to join. (ie, the parents can be checked into a 3-year-old room using Attended Checkin).

This can be tested by setting up a check-in area with "Check In By Data View" and then attempting to check in a family. You will see the parents listed, even if they do not show up in any of the data views.

**Comment by MicahO** [comment]
It occurred to me after I wrote the initial bug report that the issue might be slightly more complex. Many of our rooms use multiple data views to know who is in the room. For example, we have a room for all three-year-olds whose first names start with A-L. This is done by setting up two data views ("3 years old" and "Last Name between A-L"), BOTH of which must be satisfied to check into the room (see screenshot). It's possible that Attended Check-In is treating this combination as OR instead of AND.
![Screen Shot 2019-09-15 at 9 40 31 AM](https://user-images.githubusercontent.com/44377420/64922418-f7933300-d79c-11e9-96c9-b711ed1ed68f.png)

**Comment by MicahO** [comment]
Here's a screen capture video I did today:

https://youtu.be/UsqXNRbEFA0

**Comment by carlatKFS** [comment]
Needs to be enhanced to work with new Rock features in v9. (.e.g. Checkin by Dataview)
