### ISSUE TITLE
B: Exception updating records that have an ability level

### ISSUE THREAD

**Issue by KelleyLangkamp** [KingdomFirst/rock-attended-checkin#74]
# Expected Behavior

Expect to be able to update a child's record if they have an ability level on their record

# Current Behavior

If they have an ability level they are unable to make updates to the child's record

# Failure Information (for bugs)

![image](https://user-images.githubusercontent.com/12735965/69646851-20059c00-102e-11ea-8c16-3c12a6310a61.png)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Rock Version: v9.1
* Attended Check-in Version: 1.7

**Comment by karenn-ccbc** [comment]
I can confirm that we are seeing this issue.
