### ISSUE TITLE
Can't get labels to print

### ISSUE THREAD

**Issue by sanford-rock** [KingdomFirst/rock-attended-checkin#82]
The users replaced their laptop they had been using for Attended Checkin with a Zebra label printer USB attached to the laptop and everything worked great. However, now they cannot get check-in labels to print. You can send a test print page to the printer from Windows 10 configuration and it hits the printer. What needs to be configured to get the printer to work. The existing Rock Check-in Devices are unchanged from previously.

Thanks

**Comment by KelleyLangkamp** [comment]
This sounds more like a Rock kiosk configuration issue more than an issue with attended check-in. Does the new laptop have a kiosk created for it in Rock that matches by IP Address or Kiosk Name? Unless you specifically configured it to do manual configuration, attended check-in is going to use the printer settings from the Rock kiosk that matches the IP address or name of the computer.

Have you tried doing standard Rock check-in on that laptop and are you able to print the check-in labels using the same kiosk configuration?

**Comment by sanford-rock** [comment]
Thanks for the reply Kelly...I think their problem may be their ip address of the new laptop as the kiosk. Here's the current device setup which should be working...

[cid:cd84c3f2-6d92-4459-b4c6-0c34340ecbeb]

Richard Sanford | IT Database Coordinator

Brookwood Church
580 Brookwood Point Place
Simpsonville, SC 29681

Business: 864.688.8251
Mobile: 864.354.4004
e richard.sanford@brookwoodchurch.org<mailto:richard.sanford@richard.sanford@brookwoodchurch.org>
w www.brookwoodchurch.org<http://www.brookwoodchurch.org>
________________________________
