### ISSUE TITLE
Error when loading attended checkin

### ISSUE THREAD

**Issue by jardine98** [KingdomFirst/rock-attended-checkin#83]
I just updated to 10.3 and now I get an error when I start up attended checkin. It says that wasn't supposed to happen. Here is a screenshot of the error.

![image](https://user-images.githubusercontent.com/54868401/89055444-3bd4e680-d30f-11ea-91c1-610286e4570b.png)

**Comment by KelleyLangkamp** [comment]
I have seen issues with core check-in on Macs and this looks like the same thing. If you clear your cookies, do you get the same error? Do you have any Windows check-in kiosks? Are you getting that exception on those too?

**Comment by jardine98** [comment]
We are getting this error on our windows checking stations.

**Comment by KelleyLangkamp** [comment]
Can you do me a favor and click on the Show Cookies button in your exception log and send me a screenshot of that? Thanks!

**Comment by jardine98** [comment]
Here you go!

Thank you,
Crista Jardine   Database Administrator

Gold Creek Community Church
p:  (425) 316-3333
w:  goldcreek.org
e:  *crista*@goldcreek.org <crista@goldcreek.org>
This message is intended only for the individual(s) named. If you are not
the intended recipient, you are hereby notified that disclosing, copying,
distributing or taking any actions in reliance on the contents of this
information is strictly prohibited. Please notify the sender immediately if
you have received this email by mistake.

**Comment by jardine98** [comment]
I don't mean to seem impatient but do you know if this is an error on my
end or if the app needs to be updated?

Thank you,
Crista Jardine   Database Administrator

Gold Creek Community Church
p:  (425) 316-3333
w:  goldcreek.org
e:  *crista*@goldcreek.org <crista@goldcreek.org>
This message is intended only for the individual(s) named. If you are not
the intended recipient, you are hereby notified that disclosing, copying,
distributing or taking any actions in reliance on the contents of this
information is strictly prohibited. Please notify the sender immediately if
you have received this email by mistake.

**Comment by KelleyLangkamp** [comment]
Crista,

The expanded exception image did not come through. I'm not sure if it was because you replied by email vs commenting on the issue page or why that was but can you try sending that to me again?

Also, can you verify that the check-in stations have been restarted since the update?

Thanks!

**Comment by jardine98** [comment]
![image](https://user-images.githubusercontent.com/54868401/89205134-12fd5d00-d56c-11ea-957d-ba93bff07e42.png)
 Yes I just made sure that the computers were shut down and restarted and I am still getting this error.

**Comment by jardine98** [comment]
We were able to get rid of this error by deleting the Temp ASP NET files.

**Comment by KelleyLangkamp** [comment]
Thanks for letting us know.
