### ISSUE TITLE
B: Editing Location/Schedule at Confirm Page Throws Server Error

### ISSUE THREAD

**Issue by briankalwat** [KingdomFirst/rock-attended-checkin#88]
# Prerequisites
**We will take your suggestion into consideration, however, if you would like to sponsor this change, please email sales@kingdomfirstsolutions.com and we will process an estimate for you.**

**Otherwise, bugs will be addressed in the order of criticality, and enhancements will be addressed as sponsored, or as we have the available bandwidth. Note: Our code may not be vetted for, and may not support early release Rock versions only general release Rock versions.**

Please answer the following questions for yourself before submitting an issue. 

- [x] I have classified my issue according to the following rules:

**Bug Classifications:**

_Enhancement:_ A desired change to the code that enhances functionality verses fixing an issue.   

_Bug:_ Updating code to work as originally designed.

_Block Name:_ Every Bug should be labeled with the name of the Block the bug is related to. (No Attended Checkin or Bulldozer)

- [x] I am running the latest version (1.8.3)
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository: generally https://github.com/KingdomFirst/RockBlocks
- [x] I've named my issue either `B:` or `E:` depending on whether it is a bug or an enhancement

# Expected Behavior

You should be able to edit and change the assigned Location/Schedule for a person who is checking in.

# Current Behavior

Attempting to edit Location/Schedule throws a server error.

# Failure Information (for bugs)

![image](https://user-images.githubusercontent.com/2465823/119361248-74b4c200-bc79-11eb-8f0c-73c353c455b0.png)

Stack Trace:

```
[InvalidOperationException: ListView with id 'lvLocation' must have a data source that either implements ICollection or can perform data source paging if AllowPaging is true.]
   System.Web.UI.WebControls.ListView.CreateChildControls(IEnumerable dataSource, Boolean dataBinding) +1622
   System.Web.UI.WebControls.ListView.PerformDataBinding(IEnumerable data) +64
   System.Web.UI.WebControls.DataBoundControl.OnDataSourceViewSelectCallback(IEnumerable data) +207
   System.Web.UI.WebControls.ListView.PerformSelect() +127
   RockWeb.Plugins.cc_newspring.AttendedCheckin.ActivitySelect.BindLocations(List`1 groupTypes, Nullable`1 groupTypeId, Nullable`1 groupId, Nullable`1 locationId) in F:\wwwroot\Plugins\cc_newspring\AttendedCheckIn\ActivitySelect.ascx.cs:958
   RockWeb.Plugins.cc_newspring.AttendedCheckin.ActivitySelect.OnLoad(EventArgs e) in F:\wwwroot\Plugins\cc_newspring\AttendedCheckIn\ActivitySelect.ascx.cs:166
   System.Web.UI.Control.LoadRecursive() +154
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3386
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. 

1. Update Rock to pre-alpha release 13.0.13.
2. Check anyone in up to the /attendedcheckin/confirm page
3. Attempt to edit the Location/Schedule you're checking the person into
4. See server error

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Rock Version: 13.0.13
* Attended Check-in Version: 1.8.3
* SQL Server Version: Azure SQL
* Windows Version: Server 2019 Datacenter

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by briankalwat** [comment]
@nateh777 any thoughts on this? Would you like me to log this issue elsewhere, or is this best place for it? Thanks man!

**Comment by nateh777** [comment]
hi @briankalwat, I took a brief look at this when you submitted it, unfortunately v13 is changing a lot behind the scenes and I am not positive what is breaking this, I believe it has to do with the Lava changes which change some of the core collection references. We do not actively develop on the develop branch and as such v13 is not fully supported by our plugins. 

We have it on our list to look into it as soon as we can, but it takes a bit of work due to that. We understand this is an issue for you guys, but are unfortunately not able to get to it right away. If you would like to sponsor us looking into it sooner we are happy to do so as our schedule allows. Please email sales@kingdomfirstsolutions.com for further discussion.

**Comment by nateh777** [comment]
@briankalwat would it be possible for you to produce a video of the issue? I was able to get an environment setup with the develop branch (Rock About is showing 1.13.0.14) and I was not able to produce the issue. I did however have to update the attended check in project to 4.7.2 to build properly. Are you guys running out of the RockShop version or the github project? Here is a rebuilt version of the DLL for 4.7.2 if it is what fixed it for me: https://kingdomfirstsolutions-my.sharepoint.com/:u:/p/nateh/ERWMD_MZIP1DgcAyR4Vc1mMBQqzt2MP0hbDhuWZUx1G0pQ?e=bG6kaM

**Comment by briankalwat** [comment]
@nateh777 We are running off the Rock Shop version. We spoke with Spark last week and they were able to implement a fix that we cherry-picked that added backwards compatibility for Attended Check-In, so as of now I think we're in good shape. https://github.com/SparkDevNetwork/Rock/commit/f9f1e4fb8009e4da999bf97861f91db9aabffe03

**Comment by nateh777** [comment]
Well, I guess that is why it worked for me as they committed that the day I tested... what are the chances. Thank you for letting us know. We'll have it on the list for a future update after v13 is generally available.
